source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyForm_Example' do
  pod "EasyForm", :path => "../"
end

target 'EasyForm_Tests' do
  pod "EasyForm", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
