# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.2
podfile: Example/Podfile
before_install:
#- rvm use system
#- sudo gem install cocoapods --no-rdoc --no-ri --no-document --quiet
#- sudo gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod install
script:
- set -o pipefail && xcodebuild test -workspace Example/EasyForm.xcworkspace -scheme EasyForm-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

