# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8.2
xcode_project: Example/EasyForm.xcworkspace
xcode-scheme: EasyForm-Example
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/EasyForm.xcworkspace -scheme "EasyForm-Example" -sdk iphonesimulator -destination "OS=10.1,name=iPhone 7" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
- pod lib lint
